version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: nestjs-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - monitoring
  
  storage:
    build: ./s3
    container_name: s3
    ports:
      - 9000:9000
    networks:
      - monitoring
  
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - 9090:9090
      networks:
      - monitoring
      environment:
        - APP_HOST=app:5000
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3100:3000
    depends_on:
      - prometheus
    networks:
      - monitoring
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - monitoring
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - monitoring

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - monitoring

volumes:
  db-data:
  grafana-data:
  esdata:
networks:
  monitoring:
    driver: bridge
