version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: nestjs-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
